/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajofinal;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTabbedPane;

/**
 *
 * @author Luis Miguel Fung
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelKnn = new javax.swing.JPanel();
        txtknnDiv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKnnK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaKnnMC = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaKnnR = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnKnnComenzar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanelNaiveBayes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNaiveHP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNaiveDiv = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaNaiveMC = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaNaiveR = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnNaiveComenzar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnBotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabajo Final");

        jPanelKnn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Ingrese la cantidad de divisiones para el dataset:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Ingrese un k para los vecinos mas cercanos");

        txtAreaKnnMC.setColumns(20);
        txtAreaKnnMC.setRows(5);
        jScrollPane1.setViewportView(txtAreaKnnMC);

        txtAreaKnnR.setColumns(20);
        txtAreaKnnR.setRows(5);
        jScrollPane2.setViewportView(txtAreaKnnR);

        jLabel3.setText("Resultados:");

        btnKnnComenzar.setText("Comenzar");
        btnKnnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnnComenzarActionPerformed(evt);
            }
        });

        jLabel7.setText("Matriz de Confusion");

        javax.swing.GroupLayout jPanelKnnLayout = new javax.swing.GroupLayout(jPanelKnn);
        jPanelKnn.setLayout(jPanelKnnLayout);
        jPanelKnnLayout.setHorizontalGroup(
            jPanelKnnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKnnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKnnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKnnLayout.createSequentialGroup()
                        .addComponent(btnKnnComenzar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelKnnLayout.createSequentialGroup()
                        .addGroup(jPanelKnnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKnnK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtknnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanelKnnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanelKnnLayout.setVerticalGroup(
            jPanelKnnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKnnLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelKnnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKnnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKnnLayout.createSequentialGroup()
                        .addComponent(txtknnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(txtKnnK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnKnnComenzar)
                .addContainerGap())
        );

        jTabbedPane.addTab("Knn", jPanelKnn);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Ingrese la cantidad de divisiones para el dataset:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Ingrese el valor para el hiperparametro:");

        txtAreaNaiveMC.setColumns(20);
        txtAreaNaiveMC.setRows(5);
        jScrollPane3.setViewportView(txtAreaNaiveMC);

        jLabel6.setText("Resultados:");

        txtAreaNaiveR.setColumns(20);
        txtAreaNaiveR.setRows(5);
        jScrollPane4.setViewportView(txtAreaNaiveR);

        jLabel8.setText("Matriz de Confusion");

        btnNaiveComenzar.setText("Comenzar");
        btnNaiveComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaiveComenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNaiveBayesLayout = new javax.swing.GroupLayout(jPanelNaiveBayes);
        jPanelNaiveBayes.setLayout(jPanelNaiveBayesLayout);
        jPanelNaiveBayesLayout.setHorizontalGroup(
            jPanelNaiveBayesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaiveBayesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNaiveBayesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaiveHP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaiveDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNaiveComenzar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanelNaiveBayesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanelNaiveBayesLayout.setVerticalGroup(
            jPanelNaiveBayesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaiveBayesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNaiveBayesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGroup(jPanelNaiveBayesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNaiveBayesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaiveDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaiveHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanelNaiveBayesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btnNaiveComenzar)
                .addContainerGap())
        );

        jTabbedPane.addTab("Naive Bayes", jPanelNaiveBayes);

        btnCargar.setText("Cargar Arff");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnBotonSalir.setText("Salir");
        btnBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(606, 606, 606)
                        .addComponent(btnBotonSalir))
                    .addComponent(btnCargar)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        //Creamos el objeto JFileChooser
        JFileChooser fc=new JFileChooser();
 
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion=fc.showOpenDialog(jTabbedPane);
 
        //Si el usuario, pincha en aceptar
        if(seleccion==JFileChooser.APPROVE_OPTION){
 
            //Seleccionamos el fichero
            File fichero = fc.getSelectedFile();
            ruta = fichero.getAbsolutePath();
           
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBotonSalirActionPerformed

    private void btnKnnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnnComenzarActionPerformed
        // TODO add your handling code here:
       
        
        LeerDataset leer = new LeerDataset();
        String cadena = txtknnDiv.getText();
        String cadena2 = txtKnnK.getText();
        Integer numDiv = Integer.valueOf(cadena);
        Integer k = Integer.valueOf(cadena2);
        try {
            leer.cargarData(ruta);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
        Knn knn = new Knn();
        knn.algoritmo(numDiv, k, leer.getDataset());
        Integer instancias = 0;
        for (int m = 0; m < knn.getMatrizConfusion().size(); m++)
        {
                txtAreaKnnMC.append(m + " ");
                for (int j = 0; j < knn.getMatrizConfusion().get(0).size(); j++) {
                        
                        txtAreaKnnMC.append(knn.getMatrizConfusion().get(m).get(j).toString() + " ");
                        
                        instancias += knn.getMatrizConfusion().get(m).get(j);
                }
                txtAreaKnnMC.append("\n");
                
        }
        txtAreaKnnMC.append(instancias.toString() + "\n\n");
        for (int i = 0; i < 22; i++) {
             txtAreaKnnR.append(leer.getDataset().getTipoAtributos().get(17).get(i) +"\n ");
             txtAreaKnnR.append("TasaVP: " + knn.getResultados().get(i).get(0)+" ");
             txtAreaKnnR.append("TasaFP: " + knn.getResultados().get(i).get(1)+" ");
             txtAreaKnnR.append("accuracy: " + knn.getResultados().get(i).get(2)+"\n");
             txtAreaKnnR.append("Recall: " + knn.getResultados().get(i).get(3)+" ");
             txtAreaKnnR.append("Precision: " + knn.getResultados().get(i).get(4)+" ");
             txtAreaKnnR.append("FMeasure: " + knn.getResultados().get(i).get(5)+"\n");             
        }
        txtAreaKnnR.append("\n");
         
        
        txtknnDiv.setText(""); 
        txtKnnK.setText("");
    }//GEN-LAST:event_btnKnnComenzarActionPerformed

    private void btnNaiveComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaiveComenzarActionPerformed
        // TODO add your handling code here:
        LeerDataset leer = new LeerDataset();
        String cadena = txtNaiveDiv.getText();
        String cadena2 = txtNaiveHP.getText();
        Integer numDiv = Integer.valueOf(cadena);
        Integer hp = Integer.valueOf(cadena2);
        try {
            leer.cargarData(ruta);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
        NaiveBayes nb = new NaiveBayes();
        nb.algoritmo(hp, numDiv, leer.getDataset());
        Integer instancias = 0;
        for (int m = 0; m < nb.getMatrizConfusion().size(); m++)
        {
                txtAreaNaiveMC.append(m + " ");
                for (int j = 0; j < nb.getMatrizConfusion().get(0).size(); j++) {
                        
                        txtAreaNaiveMC.append(nb.getMatrizConfusion().get(m).get(j).toString() + " ");
                        
                        instancias += nb.getMatrizConfusion().get(m).get(j);
                }
                txtAreaNaiveMC.append("\n");
                
        }
        txtAreaNaiveMC.append(instancias.toString() + "\n\n");
        for (int i = 0; i < 22; i++) {
             txtAreaNaiveR.append(leer.getDataset().getTipoAtributos().get(17).get(i) +"\n ");
             txtAreaNaiveR.append("TasaVP: " + nb.getResultados().get(i).get(0)+" ");
             txtAreaNaiveR.append("TasaFP: " + nb.getResultados().get(i).get(1)+" ");
             txtAreaNaiveR.append("accuracy: " + nb.getResultados().get(i).get(2)+"\n");
             txtAreaNaiveR.append("Recall: " + nb.getResultados().get(i).get(3)+" ");
             txtAreaNaiveR.append("Precision: " + nb.getResultados().get(i).get(4)+" ");
             txtAreaNaiveR.append("FMeasure: " + nb.getResultados().get(i).get(5)+"\n");             
        }
        txtAreaNaiveR.append("\n");
         
        
        txtNaiveDiv.setText(""); 
        txtNaiveHP.setText("");
    }//GEN-LAST:event_btnNaiveComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        // Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        
        
        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotonSalir;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnKnnComenzar;
    private javax.swing.JButton btnNaiveComenzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelKnn;
    private javax.swing.JPanel jPanelNaiveBayes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea txtAreaKnnMC;
    private javax.swing.JTextArea txtAreaKnnR;
    private javax.swing.JTextArea txtAreaNaiveMC;
    private javax.swing.JTextArea txtAreaNaiveR;
    private javax.swing.JTextField txtKnnK;
    private javax.swing.JTextField txtNaiveDiv;
    private javax.swing.JTextField txtNaiveHP;
    private javax.swing.JTextField txtknnDiv;
    // End of variables declaration//GEN-END:variables
    private String ruta;
   
}
